export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const RESET_SERVICE_FORM = "RESET_SERVICE_FORM";
export const EDIT_SERVICE_FORM = "EDIT_SERVICE_FORM";
export const EDIT_SERVICE_STATE = "EDIT_SERVICE_STATE";
export const CHANGE_SERVICE_SEARCH_FIELD = "CHANGE_SERVICE_SEARCH_FIELD";
export const FILTER_SERVICE = "FILTER_SERVICE";
export const CLEAR_FILTER_SERVICE = "CLEAR_FILTER_SERVICE";

