export const ADD_SERVICE = "ADD_SERVICE";
export const REMOVE_SERVICE = "REMOVE_SERVICE";
export const UPDATE_SERVICE = "UPDATE_SERVICE";
export const CHANGE_SERVICE_FIELD = "CHANGE_SERVICE_FIELD";
export const RESET_SERVICE_FORM = "RESET_SERVICE_FORM";
export const EDIT_SERVICE_FORM = "EDIT_SERVICE_FORM";
export const EDIT_SERVICE_STATE = "EDIT_SERVICE_STATE";

